import Head from "next/head";
import { DataContext } from "../store/GlobalState";
import { useState, useContext, useEffect } from "react";

export default function Home() {
	const { state, dispatch } = useContext(DataContext);

	return (
		<div>
			<div>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
			
				
			</div>
		</div>
	);
}
